[[redirects]]
  from = "/api/*"
  to = "https://api.codexpace.com/api/:splat"
  status = 200
  force = true


[[redirects]]
  from = "/media/*"
  to = "https://api.codexpace.com/media/:splat"
  status = 200
  force = true


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200